Mobile protofolio
Abdo9826/protofolio pull request #1
Opened 2022-04-21 19:38 UTC by Abdo9826

setup and mobile version skeleton with HTML and CSS

2022-04-21 20:04 UTC, ShahierNashaat requested changes
Hi @Abdo9826 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Please add the setup steps in your readme file.
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-21 20:04 UTC, ShahierNashaat commented on index.html
> +</div>
- [x] Kindly remove this div as it is the header of the phone and you shouldn't design it.

2022-04-21 20:04 UTC, ShahierNashaat commented on index.html
> +<h4>Abdo</h4>
- [x] Kindly put this in an `a` tag.

2022-04-21 20:04 UTC, ShahierNashaat commented on index.html
> +<P class="img"><img src="image/Union.png" alt=""></P>
- [x] Please be noticed that only the hamburger button is the one that should be inside the `nav` tag.

2022-04-21 20:04 UTC, ShahierNashaat commented on index.html
> +        </header>
- [x] Kindly be noticed that only the logo and the hamburger button are the ones that should be inside the `header` tag.

2022-04-21 20:04 UTC, ShahierNashaat commented on a.css
> +}
- [ ] Please make your design responsive.
![Screenshot from 2022-04-21 21-54-00](https://user-images.githubusercontent.com/33752735/164543301-ddf23702-9050-4704-8bc2-f517c365c9e0.png)

2022-04-21 22:12 UTC, OLIPLICHE reviewed
Hi @Abdo9826 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that the Linter result is not green ✔️ 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-04-22 01:09 UTC, Munsa1 requested changes
Hi <STUDENT_MENTION>, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
- linters passing
- Correct gitflow

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Making your readme file more descriptive by adding a description of the project

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-22 01:09 UTC, Munsa1 commented on index.html
> +        </header>
This requested change has not been implemented, Kindly remove lines 38 to 58 from the `header` tag and create a `section` below the header where you will paste that code 
e.g
![image](https://user-images.githubusercontent.com/81932478/164575475-b9a104d1-05c3-4dfd-b381-1444a74ef0c4.png)

- The header should remain looking something like this
![image](https://user-images.githubusercontent.com/81932478/164575668-55fdb427-2720-4276-858c-e5b2cb0aa126.png)


[Optional] Note to indent your code properly as this helps find bugs easily and makes your code more readable to other collaborators.

2022-04-22 01:09 UTC, Munsa1 commented on a.css
> +  margin-left: 933px;
Again as requested by the previous reviewer your page is not responsive. Kindly remove that left margin inline `16` as it is pushing your whole page out of view in mobile view.

2022-04-22 01:09 UTC, Munsa1 commented on index.html
> +
As requested by the previous reviewer, these Icons are not part of the Figma template rather they just serve to show that the site is being viewed on a phone. Kindly remove them and leave the only the logo_name and the mobile menu_bar

2022-04-22 08:18 UTC, danmainah approved these changes
Hi @Abdo9826 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 

## Highlights

✔️ No linter errors
✔️ Github flow was correctly used
✔️  Good PR and Description

## Optional suggestions

- [ ] Kindly make sure your page is responsive, currently, it works but it has a fixed width which is not a good design.
- [ ] Please consider adding more content in your `readme` file, especially in the Getting Started section and acknowledgement section.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me using @danmainah in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-22 08:27 UTC, merged