Add popup-Window
Abdo9826/protofolio pull request #11
Opened 2022-05-11 21:18 UTC by Abdo9826

Add HTML codes 
Add CSS styles 
Add Js codes

2022-05-11 22:18 UTC, youmari requested changes
Hi @Abdo9826 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are 

## Highlights
✔️ No linter error
✔️ Great title and short summary

## Required Changes ♻️

- [ ] [OPTIONAL] You have a space gap in the headline please try to remove it in order to match the Figma design 
- [ ] [OPTIONAL] please try to name your files a better name than `a` as you did that will make your project a bit messy and not understandable by other developers  

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-11 22:18 UTC, youmari commented on a.js
> +});
- [ ] I see that you hardcoded the projects cards they should generate dynamically with `Javascript` in order to be easy for you to add more cards, so please try to implement that and  create the cards in javascript dynamically as  in the requirements 
![image](https://user-images.githubusercontent.com/61790587/167956300-e0884c78-3743-4293-8a3c-59ceeceb1112.png)

2022-05-11 22:18 UTC, youmari commented on a.css
> +    font-weight: 400;
- [ ] I see that you are using a transparent background for your pop up window it should be white as in the Figma design so please try to fix that 

- [ ] Figma design 
![image](https://user-images.githubusercontent.com/61790587/167954806-71fd1a60-4e4a-4170-b332-0f02e8d0e7db.png)

- [ ] Yours 
![image](https://user-images.githubusercontent.com/61790587/167954854-ace2cf68-ffb6-4af6-ba0f-d64de043b5b1.png)

2022-05-12 23:14 UTC, smunozmo requested changes
Hi @Abdo9826 , 👋  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights 👏 

- Great work using the right GitHub Flow.
- Your README looks professional, well done!
- Commits are descriptive, good work.
- Linters are working properly, great job!


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- [OPTIONAL] It would be better to use meaningful names for your files, this way your repository will look more professional for recruiters and other developers.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

<img src="https://media1.giphy.com/media/z5cNqbFbMTDA4/giphy.gif"/>


Cheers and Happy coding! 🤓 

✅  Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

⚠️  **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-12 23:14 UTC, smunozmo commented on index.html
> +       <!-- <div class="mainbody"> -->
- [ ] Pop-up window is looking great! However, as the previous reviewer said, the content of the pop-up window and the works section should be created dynamically, this means that all the hardcoded info from line 66 to 253 should be deleted and it should be loaded using DOM manipulation with JavaScript. The goal is to have an array with all the data from the projects and create a function that adds all the HTML elements to the DOM. 

Please remove all the hardcoded info from the HTML and use JS to load it dynamically.

2022-05-13 15:44 UTC, smunozmo approved these changes
Hi @Abdo9826, 👋 

## Highlights 👏 

- Great work using the right GitHub Flow.
- Your README looks professional, well done!
- Commits are descriptive, good work.
- Linters are working properly, great job!

Your project is complete!  There is nothing else to say other than... it's time to merge it! 🚀 
Very nice work, congratulations! 🎉 

### APPROVED! 💯  💯  💯 

<img src="https://media4.giphy.com/media/cFkiFMDg3iFoI/giphy.gif"/>


Cheers and Happy coding! 🤓 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

✅  Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-13 15:44 UTC, smunozmo commented on index.html
> +          <!-- <img class="none" id="img1" src="image/img1.png" alt="Multi-Post Stories image">
[OPTIONAL] Now that your content is created dynamically, it would be great to clean up your HTML file by removing any unused code.

2022-05-13 15:49 UTC, merged